config/routes.rb
FriendCircle::Application.routes.draw do
  root to: "users#show"
  resources :users, only: [:show, :new, :create, :edit, :update] do
    resources :circles
    resources :posts, only: [:new]
    get :feed, to: "users#feed"
  end
  resources :posts, only: [:create, :edit, :update, :destroy, :show]
  resource :reset, only: [:new, :create, :edit, :update]
  resource :session, only: [:new, :create, :destroy]
end

app/views/shared/_user_form.html.erb
<% title = (params[:controller] == "sessions" ? "Log In" : "Sign Up") %>
<% action_url = (params[:controller] == "sessions" ? session_url : users_url)%>

<h1><%= title %></h1>

<form action="<%= action_url %>" method="POST">
  <%= csrf_token %>

  <label>
    E-mail Address
    <input type="text" name="user[email]" value="<%=@user.email%>">
  </label>
  <br>
  <label>
    Password
    <input type="password" name="user[password]">
  </label>

  <%= "<!--".html_safe unless params[:controller] == "users"%>

  <h2>Create Your First Post!</h2>

  <label>Post
    <input type="textarea" name="post[body]" value="<%= @post.body %>">
  </label>

  <% @post.links.each_with_index do |link, i| %>
    <p>
    <label>
      Link Title
      <input type="text"
         name="links[<%=i%>][title]"
         value="<%=@post.links[i].title%>">
    </label>
    <label>
      Link URL
      <input type="text"
             name="links[<%=i%>][url]"
             value="<%=@post.links[i].url%>"
    </label>
    </p>
  <% end %>
  <%= "-->".html_safe unless params[:controller] == "users" %>

  <input type="submit" value="<%=title%>">
  <br>
  <%= (link_to "Forgot Password?", new_reset_url) if params[:controller] == "sessions"%>
</form>