config/routes.rb
FriendCircle::Application.routes.draw do
  root to: "users#show"
  resources :users, only: [:show, :new, :create, :edit, :update] do
    resources :circles
    resources :posts, only: [:new]
    get :feed, to: "users#feed"
  end
  resources :posts, only: [:create, :edit, :update, :destroy, :show]
  resource :reset, only: [:new, :create, :edit, :update]
  resource :session, only: [:new, :create, :destroy]
end

app/controllers/resets_controller.rb
class ResetsController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_email(params[:user][:email])
    if @user
      @user.generate_auth_token!
      if @user.save
        msg = PwReset.reset_email(@user)
        msg.deliver!
        flash[:notice] = "Password reset request sent.  Please check your e-mail."
        redirect_to new_session_url
      else
        flash.now[:errors] = @user.errors.full_message
        render :new
      end
    else
      flash.now[:errors] = "No user on file with this e-mail address."
      @user = User.new
      render :new
    end
  end

  def edit
    @user = User.find_by_auth_token(params[:auth_token])
    if @user
      render :edit
    else
      flash[:errors] = "Password reset request not authorized.  Make sure you are using the URL sent from the most recent e-mail."
      redirect_to new_session_url
    end
  end

  def update
    @user = User.find_by_auth_token(params[:auth_token])
    if @user
      @user.password = params[:password]
      if @user.save
        @user.generate_auth_token!
        @user.save!
        render :show
      else
        flash.now[:errors] = @user.errors.full_messages
        render :edit
      end
    else
      flash[:errors] = "Password reset request not authorized.  Only one password reset per e-mail."
      redirect_to new_session_url
    end
  end
end

app/helpers/resets_helper.rb
module ResetsHelper
end

app/views/resets/edit.html.erb
<h1>Reset Password</h1>
<form action="<%=reset_url%>" method="POST">
  <%= csrf_token %>

  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="auth_token" value="<%=params[:auth_token]%>">

  <label>
    New Password:
    <input type="password" name="password">
  </label>
  <input type="submit" value="Yes">
</form>

app/views/resets/new.html.erb
<h1>Reset Password</h1>

<form action="<%= reset_url %>" method="POST">
  <%= csrf_token %>

  <label>
    E-mail Address
    <input type="text" name="user[email]" value="<%=@user.email%>">
  </label>

  <input type="submit" value="Reset">
  <br>
</form>

app/views/resets/show.html.erb
<h1>Password Reset!</h1>
Your password has been successfully reset.
<br><br>
<%= link_to "Sign In Now", new_session_url%>