config/routes.rb
FriendCircle::Application.routes.draw do
  root to: "users#show"
  resources :users, only: [:show, :new, :create, :edit, :update] do
    resources :circles
    resources :posts, only: [:new]
    get :feed, to: "users#feed"
  end
  resources :posts, only: [:create, :edit, :update, :destroy, :show]
  resource :reset, only: [:new, :create, :edit, :update]
  resource :session, only: [:new, :create, :destroy]
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  body       :string(255)      not null
#  user_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  validates :body, :user, :presence => true

  belongs_to :user, :inverse_of => :owned_posts
  has_many :links, :inverse_of => :post
  has_many :post_shares, :inverse_of => :post
  has_many :circles, :through => :post_shares
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_logged_in
  before_action :set_user
  before_action :verify_ownership, only: [:edit, :update, :destroy]

  def new
    @post = current_user.owned_posts.build
    3.times { @post.links.build }
    render :new
  end

  def edit
    @links = @post.links
    render :edit
  end

  def update
    @post.update_attributes(post_params)
    @links = @post.links.map { |link| link.update(link_params.first) }
    @post.circle_ids = params.require(:post).permit(:circle_ids => []).values.flatten
    if @post.save
      flash[:notice] = "Post updated!"
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def create
    @post = @user.owned_posts.new(post_params)
    @links = @post.links.new(link_params)
    @post.circle_ids = params.require(:post).permit(:circle_ids => []).values.flatten
    if @post.save
      flash[:notice] = "Post created!"
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      (3 - @post.links.count).times {@post.links.build}
      render :new
    end
  end

  def destroy
    @post ||= Post.find(params[:id])
    @post.destroy!
    redirect_to user_url(@user)
  end

  def show
    #Todo: only allow showing for those with whom post is shared
    @post = Post.find(params[:id])
    render :show
  end


  def post_params
    params.require(:post).permit(:body, :user_id)
  end

  def link_params
    params.permit(:links => [:url, :title])
          .require(:links)
          .values
          .reject { |data| data.values.all?(&:blank?) }
  end

  def set_user
    @user = current_user
  end

  def verify_ownership
    @post ||= Post.find(params[:id])
    redirect_to user_url(current_user) unless @post.user_id == @user.id
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% action = (@post.persisted? ? post_url(@post) : posts_url) %>
<% title = (@post.persisted? ? "Edit Post" : "Create Post")%>

<form action="<%= action %>" method="POST">
  <%= csrf_token %>
  <% if @post.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <input type="hidden" name="post[user_id]" value="<%= @user.id %>">

  <input type="textarea" name="post[body]" value="<%= @post.body %>">

  <% @user.owned_circles.each_with_index do |circle, i| %>
    <label><%= circle.name %>
    <input type="checkbox" name="post[circle_ids][]" value="<%=circle.id%>"
           <%= @post.circle_ids.include?(circle.id) ? 'checked' : '' %> >
    </label>
  <% end %>

  <% @post.links.each_with_index do |link, i| %>
    <p>
    <label>
      Link Title
      <input type="text"
         name="links[<%=i%>][title]"
         value="<%=@post.links[i].title%>">
    </label>
    <label>
      Link URL
      <input type="text"
             name="links[<%=i%>][url]"
             value="<%=@post.links[i].url%>"
    </label>
    </p>
  <% end %>

  <%= "<!--".html_safe if params[:controller] == "users"%>
  <input type="submit" value="<%= title %>">
  <%= "-->".html_safe if params[:controller] == "users"%>
</form>

app/views/posts/edit.html.erb
<%= render "form" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<h1>Viewing Post</h1>
<%= link_to "Edit Post", edit_post_url(@post)%>

<% @post.links.each do |link| %>
  <p><%= link_to link.title, link.url%></p>
<% end %>
<p><%= @post.body %></p>