config/routes.rb
FriendCircle::Application.routes.draw do
  root to: "users#show"
  resources :users, only: [:show, :new, :create, :edit, :update] do
    resources :circles
    resources :posts, only: [:new]
    get :feed, to: "users#feed"
  end
  resources :posts, only: [:create, :edit, :update, :destroy, :show]
  resource :reset, only: [:new, :create, :edit, :update]
  resource :session, only: [:new, :create, :destroy]
end

app/models/circle.rb
# == Schema Information
#
# Table name: circles
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  owner_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class Circle < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => {scope: :owner_id}
  validates :owner, :presence => true

  has_many :circle_memberships, :inverse_of => :circle
  has_many :users, through: :circle_memberships

  has_many :post_shares, :inverse_of => :circle
  has_many :posts, :through => :post_shares, :source => :post

  belongs_to :owner, class_name: "User", inverse_of: :owned_circles
end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController
  before_action :set_user
  before_action :verify_user

  def index
    render :index
  end

  def show
    @circle = Circle.find(params[:id])
    render :show
  end

  def new
    @circle = @user.circles.build
    render :new
  end

  def create
    @circle = @user.owned_circles.new(circle_params)
    #@circle.circle_memberships.new(users_params)
    if @circle.save
      flash[:notice] = "Circle #{@circle.name} created!"
      redirect_to user_circles_url(current_user)
    else
      flash.now[:errors] = @circle.errors.full_messages
      render :new
    end
  end

  def edit
    @circle = Circle.find(params[:id])
    render :edit
  end

  def update
    @circle = Circle.find(params[:id])
    @circle.update_attributes(circle_params)
    if @circle.save
      flash[:notice] = "Circle #{@circle.name} updated!"
      redirect_to user_circle_url(current_user, @circle)
    else
      flash.now[:errors] = @circle.errors.full_messages
      render edit
    end
  end

  def destroy
    @circle = Circle.find(params[:id])
    @circle.destroy!
    redirect_to user_circles_url(current_user)
  end

  def users_params
    params.require(:circle)
          .permit(:users => {:user_ids => []})
          .values
  end

  def circle_params
    params.require(:circle).permit(:name, :user_ids => [])
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/views/circles/_form.html.erb
<% action = (params[:action] == 'new' ? user_circles_url : user_circle_url)%>
<% title = (params[:action] == "new" ? "New Circle" : "Edit Circle")%>

<h1><%= title %></h1>

<form action="<%= action %>" method="POST">
  <%= csrf_token %>
  <%= "<input type=\"hidden\" name=\"_method\" value=\"PATCH\"".html_safe if params[:action] == "edit" || params[:action] == "update" %>

  <input type="hidden" name="circle[owner_id]" value="<%=@user.id%>">
  <input type="hidden" name="circle[user_ids][]" value="" ">

  <label>
    Name
    <input type="text" name="circle[name]" value="<%=@circle.name%>">
  </label>

  <p>
  <% User.all.each_with_index do |user, i| %>
  <label>
    <%= user.email %>
    <input type="checkbox" name="circle[user_ids][]" value="<%=user.id%>"
           <%= @circle.user_ids.include?(user.id) ? 'checked' : '' %> >
  </label>
  <% end %>
  </p>

  <p>
  <input type="submit" value="<%= title %>">
  </p>
</form>

app/views/circles/_show_circles.html.erb
<% @user.owned_circles.each do |circle| %>
  <%= link_to circle.name, user_circle_url(@user, circle)%>
  <%= link_to "(Modify This Circle)", edit_user_circle_url(@user, circle)%><br>
<% end %>

<br>
<%= link_to "Create a New Circle", new_user_circle_url(@user)%>

app/views/circles/edit.html.erb
<%= render "form" %>

app/views/circles/index.html.erb
<h1>Your Circles</h1>

<%= render "show_circles" %>

app/views/circles/new.html.erb
<h1>New Circle</h1>

<form action="<%= user_circles_url %>" method="POST">
  <%= csrf_token %>
  <input type="hidden" name="circle[owner_id]" value="<%=@user.id%>">

  <label>
    Name
    <input type="text" name="circle[name]" value="<%=@circle.name%>">
  </label>

  <p>
  <% User.all.each_with_index do |user, i| %>
  <label>
    <%= user.email %>
    <input type="checkbox" name="circle[user_ids][]" value="<%=user.id%>">
  </label>
  <% end %>
  </p>

  <p>
  <input type="submit" value="Create Circle">
  </p>
</form>

app/views/circles/show.html.erb
<h1>Placeholder Circle Show template is go</h1>
<br><br>
Circle Members:
<% @circle.users.each do |user| %>
  <%= user.email %><br>
<% end %>
<br>
<%= link_to "Edit This Circle", edit_user_circle_url(current_user, @circle)%>